### ISSUE TITLE
Usbong iOS default tree ends after choosing a class (e.g. Warrior, Rogue, Mage)

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/Usbong-iOS#1]
Salut! I've finally tested the Usbong app (iOS) on an actual device, and I noticed that the default tree ends after choosing a class (e.g. Warrior, Rogue, Mage). The default tree that I use for the Usbong app (Android) includes other questions, such as "What is your name?", "What is 1+1?". Could it be that the default tree that is used in Usbong app (iOS) is not the updated version? Merci beaucoup! 

p.s. I like how the font of the text scales and becomes larger on an ipad.

**Comment by chrisamanse** [comment]
Yes, this app hasn't been updated in a while so it's still using the old tree.

**Comment by masarapmabuhay** [comment]
D'accord! If I want to update the .utree via Xcode, is it as simple as downloading Usbong-iOS, replacing the .utree file, and exporting the output to iTunes? Or would I still need to configure certain things apart from the ones mentioned in the LIKHA-Guide? Merci beaucoup!

**Comment by chrisamanse** [comment]
As with all apps, you would also have to update the version and build number. The build number is usually incremented every time a build is uploaded to iTunes Connect. This is because if a build with a version and build number already exists in iTunes Connect, a build with the same version and build number can't be uploaded again. Xcode will show this error before uploading.

Also, you would have to make sure you are using the correct provisioning profile and code signing identities.

**Comment by masarapmabuhay** [comment]
Je comprends. I'll upload my first iOS app using the LIKHA-Guide first, and then see if I run into issues when modifying the .utree of Usbong-iOS then. Merci beaucoup!
